### ISSUE TITLE
set auth pam_faillock before pam_unix.so disconnects while running

### ISSUE THREAD

**Issue by willtome** [RedHatOfficial/ansible-rhel7-pci-dss-role#2]
Playbook:
```
---
- name: apply PCI role
  hosts: all
  become: yes

  tasks:
  - name: Apply CIS Baseline
    include_role:
      name: redhatofficial.rhel7_pci_dss
```

 Error:
```
TASK [redhatofficial.rhel7_pci_dss : set auth pam_faillock before pam_unix.so] **********************
fatal: [wtome_test4]: FAILED! => {"changed": false, "module_stderr": "Shared connection to 34.203.221.190 closed.\r\n", "module_stdout": "Traceback (most recent call last):\r\n  File \"/tmp/ansible_J_SPnQ/ansible_module_pamd.py\", line 785, in <module>\r\n    main()\r\n  File \"/tmp/ansible_J_SPnQ/ansible_module_pamd.py\", line 752, in main\r\n    valid, msg = service.validate()\r\n  File \"/tmp/ansible_J_SPnQ/ansible_module_pamd.py\", line 656, in validate\r\n    if not current_line.is_valid()[0]:\r\nTypeError: 'bool' object is not callable\r\n", "msg": "MODULE FAILURE", "rc": 1}```

Succeeds when running with `--skip-tags accounts_passwords_pam_faillock_deny`
